### ISSUE TITLE
🛑 Cloudflare Triggered, Not Working Anymore

### ISSUE THREAD

**Issue by Mr-spShuvo** [piotrpalarz/vscode-gitignore-generator#12]
I've been using your extension for over a year now, and absolutely loved it. However, today while I was using the command palette to generate `.gitignore`, it returns code of cloudflare page as the dropdown menu and stuck there. Check out the screenshot below.

![Preview](https://user-images.githubusercontent.com/22437186/109570738-c46d6c80-7b14-11eb-93a9-4c8a5417f0ee.png)

**System Info**
Windows OS 10
VSCode v1.53.2
.gitignore Generator v1.0.2

**Comment by piotrpalarz** [comment]
@Mr-spShuvo Thanks for letting me know. It's not a problem for everyone because Cloudflare is filtering traffic based on different criteria. In your case it's probably the IP address that's causing the problem. I have an idea how to fix it and I'll try to do it this week.

**Comment by Mr-spShuvo** [comment]
@piotrpalarz Thanks for the attention. Will be wait for the update. 🚀

**Comment by piotrpalarz** [comment]
@Mr-spShuvo I managed to create an alternative API URL to bypass Cloudflare's protection and it should be working now. Make sure your editor downloads new version of the extension (v1.0.3) and let me know if that did the trick. If you have VS Code opened, close it, open it again and go to the Extensions panel. You should see the update to v1.0.3.

**Comment by Mr-spShuvo** [comment]
@piotrpalarz Woohoo! 🔥 I've tested the latest version (v1.0.3) and it works like a charm 👌. 
Thanks again for the the update. Awesome work. 🤘
