### ISSUE TITLE
Not working on linux

### ISSUE THREAD

**Issue by didinele** [piotrpalarz/vscode-gitignore-generator#2]
Attempted to create it when:

1) The file didn't exist
2) The file did exist (override)

Error: `There was a problem reaching gitignore.io. Try again.`

Details:
VSC version: 1.30.0-1543307155 (insiders)
OS: Ubuntu 18.04.1 LTS

**Comment by piotrpalarz** [comment]
Could you please confirm that it's still not working? I just tested it on Ubuntu 18.04.1 LTS and VS Code v1.30.2 and had no issues.
