### ISSUE TITLE
.gitignore generator update was broken

### ISSUE THREAD

**Issue by yahu1031** [piotrpalarz/vscode-gitignore-generator#22]
### Steps to reproduce ###
- Open vscode
- press F1
- type .gitignore generator
- select update

![image](https://user-images.githubusercontent.com/35523357/139526169-d14e85fc-76bf-48e5-94bd-fa9b3fe4b7b8.png)

**Comment by yahu1031** [comment]
UPDATE: both override and update were broken

**Comment by piotrpalarz** [comment]
@yahu1031 thanks for letting me know. It seems that the API is under maintenance right now, see here: https://www.toptal.com/developers/gitignore/api

We need to wait until it's done.
