### ISSUE TITLE
Add files to .gitignore but they are still in pending changes

### ISSUE THREAD

**Issue by DanJ210** [piotrpalarz/vscode-gitignore-generator#3]
I've had this work before but now I'm using the CMD + SHIFT + P command paletted to add files to the .gitignore which it does but the files are still showing up as changes that I can stage and commit. I thought that the files you were ignoring are supposed to disappear from that changes list so you cannot commit them.

**Comment by piotrpalarz** [comment]
If I understand correctly you're talking about that issue: https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore

It's related to the Git itself, not to the .gitignore Generator extension. Please do let me know if that helps.

**Comment by DanJ210** [comment]
Ok @piotrpalarz that sounds like that's correct. I will check that out. I'm learning the process so this was the first place I could think to go.
