### ISSUE TITLE
Fail to fetch templates when DDOS protection triggered

### ISSUE THREAD

**Issue by SR2k** [piotrpalarz/vscode-gitignore-generator#6]
Hi, sorry to disturb.

When using a proxy, which is common in China due to some network issues, DDOS protection might be triggered. Then instead of templates, the plugin will fetch the captcha HTML page:

![image](https://user-images.githubusercontent.com/23319132/70200099-6c4b8d00-174e-11ea-8e1e-32cdb8fc05f9.png)

And it seems that the plugin will continue to use caches even after manually entered captcha. Maybe considering add a clear cache command or add a captcha enter window?

**Comment by Mr-spShuvo** [comment]
#12 Should be resolved with  the latest version. **v1.0.3**
